general.import = [
  "~/.config/alacritty/custom/tairiki.toml"
]

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.offset]
x = 0
y = -2

[font.glyph_offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 3
y = 3
